# Generated by Django 5.1.4 on 2024-12-22 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
        ('pizza_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzamodel',
            name='pizza_shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pizzas', to='pizza_shop.pizzashopmodel'),
            preserve_default=False,
        ),
    ]
