# Generated by Django 5.1.4 on 2024-12-23 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_pizzamodel_pizza_shop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizzamodel',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='pizzamodel',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Wednesday', max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pizzamodel',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[A-Z][a-z]{,19}$', 'Only alpha characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='pizzamodel',
            name='size',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
