# Generated by Django 5.1.4 on 2024-12-27 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_alter_pizzamodel_options_pizzamodel_day_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizzamodel',
            options={},
        ),
    ]
