# Generated by Django 5.1.4 on 2025-01-03 21:24

import core.services.file_service
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_pizzamodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzamodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to=core.services.file_service.upload_pizza_photo),
        ),
    ]
